-- Referentiels sans dependance (donnees de parametrage).

CREATE TABLE departement (
    id_departement VARCHAR(3) PRIMARY KEY,
    libelle        VARCHAR(50) NOT NULL,
    region         VARCHAR(50)
);

CREATE TABLE situation (
    id_situation INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle      VARCHAR(100) NOT NULL,
    description  TEXT
);

CREATE TABLE type_abonnement (
    id_type_abonnement INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(30) NOT NULL UNIQUE,
    libelle              VARCHAR(100) NOT NULL,
    categorie            VARCHAR(50),
    periodicite          VARCHAR(30) NOT NULL
        CHECK (periodicite IN ('journaliere', 'hebdomadaire', 'mensuelle', 'annuelle', 'sans_abonnement')),
    tarif_plein          DECIMAL(8, 2),
    description          TEXT,
    actif                BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE statut_dossier (
    id_statut INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code      VARCHAR(40) NOT NULL UNIQUE,
    libelle   VARCHAR(100) NOT NULL,
    ordre     INT,
    categorie VARCHAR(20) NOT NULL
        CHECK (categorie IN ('en_cours', 'abouti', 'rejete', 'clos'))
);

CREATE TABLE type_piece_justificative (
    id_type_piece        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                  VARCHAR(40) NOT NULL UNIQUE,
    libelle               VARCHAR(100) NOT NULL,
    description           TEXT,
    duree_validite_jours  INT
);

CREATE TABLE role_agent (
    id_role     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle     VARCHAR(50) NOT NULL,
    permissions JSONB
);

CREATE TABLE categorie_sav (
    id_categorie     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code              VARCHAR(40) NOT NULL UNIQUE,
    libelle           VARCHAR(100) NOT NULL,
    canal_prioritaire VARCHAR(20) NOT NULL
        CHECK (canal_prioritaire IN ('chatbot', 'email', 'telephone', 'chat_agent')),
    description       TEXT
);

CREATE TABLE plage_disponibilite_canal (
    id_plage          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canal              VARCHAR(20) NOT NULL
        CHECK (canal IN ('telephone', 'chat_agent', 'email')),
    jour_semaine        VARCHAR(10) NOT NULL
        CHECK (jour_semaine IN ('lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche')),
    heure_debut          TIME NOT NULL,
    heure_fin            TIME NOT NULL,
    numero_ou_adresse    VARCHAR(150),
    actif                BOOLEAN NOT NULL DEFAULT TRUE
);
