-- Agent cree tot car referencee par de nombreuses tables ulterieures
-- (dossier, piece_justificative, remboursement_aide, historique...), bien
-- qu'il appartienne thematiquement au "backoffice" (section 8 du modele).

CREATE TABLE agent (
    id_agent        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom              VARCHAR(100) NOT NULL,
    prenom           VARCHAR(100) NOT NULL,
    identifiant_pro  VARCHAR(50) NOT NULL UNIQUE,
    email            VARCHAR(150) NOT NULL UNIQUE,
    id_role          INTEGER NOT NULL REFERENCES role_agent (id_role),
    equipe           VARCHAR(100),
    actif            BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE critere_eligibilite (
    id_critere                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_type_abonnement             INTEGER NOT NULL REFERENCES type_abonnement (id_type_abonnement),
    id_situation                   INTEGER REFERENCES situation (id_situation),
    id_departement                 VARCHAR(3) REFERENCES departement (id_departement),
    age_min                        INT,
    age_max                        INT,
    seuil_quotient_familial_max    DECIMAL(10, 2),
    type_avantage                  VARCHAR(30) NOT NULL
        CHECK (type_avantage IN ('tarif_reduit', 'gratuite', 'remboursement_partiel', 'remboursement_total')),
    taux_reduction_pct             DECIMAL(5, 2),
    montant_remboursement_max      DECIMAL(8, 2),
    libelle                        VARCHAR(150) NOT NULL,
    description                    TEXT,
    date_debut_validite            DATE NOT NULL,
    date_fin_validite               DATE,
    actif                           BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE piece_requise (
    id_piece_requise   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_type_abonnement  INTEGER REFERENCES type_abonnement (id_type_abonnement),
    id_critere           INTEGER REFERENCES critere_eligibilite (id_critere),
    id_type_piece        INTEGER NOT NULL REFERENCES type_piece_justificative (id_type_piece),
    obligatoire          BOOLEAN NOT NULL DEFAULT TRUE,
    commentaire          VARCHAR(200),
    CONSTRAINT chk_piece_requise_exactement_un_parent CHECK (
        (id_type_abonnement IS NOT NULL AND id_critere IS NULL)
        OR (id_type_abonnement IS NULL AND id_critere IS NOT NULL)
    )
);
