CREATE TABLE utilisateur (
    id_utilisateur          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    civilite                 VARCHAR(10),
    nom                      VARCHAR(100) NOT NULL,
    prenom                   VARCHAR(100) NOT NULL,
    date_naissance           DATE NOT NULL,
    email                    VARCHAR(150) NOT NULL UNIQUE,
    telephone                VARCHAR(20),
    mot_de_passe_hash        VARCHAR(255) NOT NULL,
    date_creation_compte     TIMESTAMP NOT NULL DEFAULT now(),
    statut_compte            VARCHAR(20) NOT NULL DEFAULT 'actif'
        CHECK (statut_compte IN ('actif', 'inactif', 'suspendu'))
);

CREATE TABLE adresse (
    id_adresse        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilisateur     INTEGER NOT NULL REFERENCES utilisateur (id_utilisateur),
    type_adresse        VARCHAR(20) NOT NULL
        CHECK (type_adresse IN ('domicile', 'facturation')),
    numero_et_voie      VARCHAR(150) NOT NULL,
    code_postal         VARCHAR(10) NOT NULL,
    ville               VARCHAR(100) NOT NULL,
    id_departement      VARCHAR(3) NOT NULL REFERENCES departement (id_departement),
    pays                VARCHAR(50) NOT NULL DEFAULT 'France',
    principale          BOOLEAN NOT NULL DEFAULT FALSE
);

-- utilisateur_situation est volontairement reportee en V5 : sa colonne
-- id_dossier_justificatif reference la table dossier, creee en V4.

CREATE TABLE relation_utilisateur (
    id_relation               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilisateur_principal   INTEGER NOT NULL REFERENCES utilisateur (id_utilisateur),
    id_utilisateur_lie          INTEGER NOT NULL REFERENCES utilisateur (id_utilisateur),
    type_relation                VARCHAR(20) NOT NULL
        CHECK (type_relation IN ('parent_tuteur', 'mandataire', 'conjoint')),
    date_debut                   DATE NOT NULL,
    date_fin                     DATE,
    statut                       VARCHAR(10) NOT NULL DEFAULT 'actif'
        CHECK (statut IN ('actif', 'inactif'))
);
