CREATE TABLE support_navigo (
    id_support             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilisateur_porteur  INTEGER NOT NULL REFERENCES utilisateur (id_utilisateur),
    numero_support           VARCHAR(30) NOT NULL UNIQUE,
    type_support             VARCHAR(30) NOT NULL
        CHECK (type_support IN ('carte_physique', 'dematerialise_smartphone', 'autre_support')),
    date_emission            DATE NOT NULL,
    date_expiration          DATE,
    statut                   VARCHAR(20) NOT NULL DEFAULT 'actif'
        CHECK (statut IN ('actif', 'opposition', 'perdu', 'vole', 'expire', 'remplace'))
);

CREATE TABLE dossier (
    id_dossier                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilisateur_porteur     INTEGER NOT NULL REFERENCES utilisateur (id_utilisateur),
    id_utilisateur_payeur       INTEGER NOT NULL REFERENCES utilisateur (id_utilisateur),
    id_type_abonnement          INTEGER NOT NULL REFERENCES type_abonnement (id_type_abonnement),
    id_support                  INTEGER REFERENCES support_navigo (id_support),
    id_statut_actuel            INTEGER NOT NULL REFERENCES statut_dossier (id_statut),
    id_agent_referent           INTEGER REFERENCES agent (id_agent),
    id_dossier_precedent        INTEGER REFERENCES dossier (id_dossier),
    canal_creation               VARCHAR(20) NOT NULL
        CHECK (canal_creation IN ('en_ligne', 'agence', 'backoffice')),
    date_creation                TIMESTAMP NOT NULL DEFAULT now(),
    date_debut_droits            DATE,
    date_fin_droits               DATE,
    montant_total                 DECIMAL(8, 2) NOT NULL DEFAULT 0,
    periodicite_paiement          VARCHAR(10) NOT NULL
        CHECK (periodicite_paiement IN ('ponctuel', 'mensuel', 'annuel'))
);
