CREATE TABLE utilisateur_situation (
    id_utilisateur_situation   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilisateur              INTEGER NOT NULL REFERENCES utilisateur (id_utilisateur),
    id_situation                 INTEGER NOT NULL REFERENCES situation (id_situation),
    date_debut                   DATE NOT NULL,
    date_fin                     DATE,
    source                       VARCHAR(20) NOT NULL
        CHECK (source IN ('auto_declare', 'valide_via_dossier')),
    id_dossier_justificatif      INTEGER REFERENCES dossier (id_dossier)
);

CREATE TABLE piece_justificative (
    id_piece              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_dossier             INTEGER NOT NULL REFERENCES dossier (id_dossier),
    id_type_piece           INTEGER NOT NULL REFERENCES type_piece_justificative (id_type_piece),
    id_utilisateur_depot    INTEGER NOT NULL REFERENCES utilisateur (id_utilisateur),
    chemin_fichier          VARCHAR(255) NOT NULL,
    date_depot              TIMESTAMP NOT NULL DEFAULT now(),
    statut_validation       VARCHAR(20) NOT NULL DEFAULT 'en_attente'
        CHECK (statut_validation IN ('en_attente', 'validee', 'rejetee')),
    id_agent_validation     INTEGER REFERENCES agent (id_agent),
    date_validation         TIMESTAMP,
    motif_rejet             TEXT
);

CREATE TABLE paiement (
    id_paiement             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_dossier               INTEGER NOT NULL REFERENCES dossier (id_dossier),
    id_utilisateur_payeur     INTEGER NOT NULL REFERENCES utilisateur (id_utilisateur),
    type_paiement             VARCHAR(20) NOT NULL
        CHECK (type_paiement IN ('paiement_initial', 'mensualite', 'frais_dossier', 'remboursement')),
    montant                   DECIMAL(8, 2) NOT NULL,
    date_paiement             TIMESTAMP NOT NULL DEFAULT now(),
    mode_paiement             VARCHAR(20) NOT NULL
        CHECK (mode_paiement IN ('CB', 'prelevement_sepa', 'cheque', 'especes_agence')),
    reference_transaction     VARCHAR(100),
    statut                    VARCHAR(20) NOT NULL DEFAULT 'en_attente'
        CHECK (statut IN ('en_attente', 'valide', 'echoue', 'annule', 'rembourse'))
);

CREATE TABLE remboursement_aide (
    id_remboursement     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_dossier             INTEGER NOT NULL REFERENCES dossier (id_dossier),
    id_critere              INTEGER REFERENCES critere_eligibilite (id_critere),
    type_aide                VARCHAR(30) NOT NULL
        CHECK (type_aide IN ('remboursement_partiel', 'remboursement_total', 'subvention_departementale')),
    montant_demande          DECIMAL(8, 2) NOT NULL,
    montant_accorde          DECIMAL(8, 2),
    date_demande             TIMESTAMP NOT NULL DEFAULT now(),
    date_traitement          TIMESTAMP,
    statut                   VARCHAR(20) NOT NULL DEFAULT 'en_attente'
        CHECK (statut IN ('en_attente', 'valide', 'rejete', 'verse')),
    id_agent_traitant        INTEGER REFERENCES agent (id_agent)
);
