CREATE TABLE historique_dossier (
    id_historique     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_dossier         INTEGER NOT NULL REFERENCES dossier (id_dossier),
    date_action         TIMESTAMP NOT NULL DEFAULT now(),
    type_action          VARCHAR(40) NOT NULL CHECK (type_action IN (
        'changement_statut', 'depot_piece', 'validation_piece', 'rejet_piece',
        'paiement_enregistre', 'remboursement_traite', 'modification_information',
        'commentaire_ajoute', 'action_pour_compte_utilisateur', 'notification_envoyee'
    )),
    id_statut_avant      INTEGER REFERENCES statut_dossier (id_statut),
    id_statut_apres      INTEGER REFERENCES statut_dossier (id_statut),
    id_agent             INTEGER REFERENCES agent (id_agent),
    id_utilisateur       INTEGER REFERENCES utilisateur (id_utilisateur),
    description           TEXT
);

CREATE TABLE commentaire_echange (
    id_commentaire           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_dossier                 INTEGER NOT NULL REFERENCES dossier (id_dossier),
    id_agent_auteur            INTEGER REFERENCES agent (id_agent),
    id_utilisateur_auteur       INTEGER REFERENCES utilisateur (id_utilisateur),
    date_creation                TIMESTAMP NOT NULL DEFAULT now(),
    contenu                      TEXT NOT NULL,
    visibilite                   VARCHAR(20) NOT NULL DEFAULT 'interne'
        CHECK (visibilite IN ('interne', 'visible_utilisateur'))
);

CREATE TABLE notification (
    id_notification    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilisateur       INTEGER NOT NULL REFERENCES utilisateur (id_utilisateur),
    id_dossier            INTEGER REFERENCES dossier (id_dossier),
    id_critere            INTEGER REFERENCES critere_eligibilite (id_critere),
    type_notification      VARCHAR(40) NOT NULL CHECK (type_notification IN (
        'nouvelle_reduction_disponible', 'remboursement_disponible', 'document_manquant',
        'document_rejete', 'statut_dossier_change', 'rappel_paiement'
    )),
    titre                   VARCHAR(150) NOT NULL,
    contenu                 TEXT,
    canal                   VARCHAR(10) NOT NULL
        CHECK (canal IN ('email', 'sms', 'push', 'in_app')),
    date_creation            TIMESTAMP NOT NULL DEFAULT now(),
    date_envoi               TIMESTAMP,
    statut_envoi             VARCHAR(20) NOT NULL DEFAULT 'en_attente'
        CHECK (statut_envoi IN ('en_attente', 'envoyee', 'echec')),
    statut_lecture           VARCHAR(10) NOT NULL DEFAULT 'non_lu'
        CHECK (statut_lecture IN ('non_lu', 'lu')),
    date_lecture             TIMESTAMP
);
