CREATE TABLE session_chatbot (
    id_session             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilisateur           INTEGER REFERENCES utilisateur (id_utilisateur),
    id_dossier               INTEGER REFERENCES dossier (id_dossier),
    date_debut                TIMESTAMP NOT NULL DEFAULT now(),
    date_fin                  TIMESTAMP,
    statut                    VARCHAR(20) NOT NULL DEFAULT 'en_cours'
        CHECK (statut IN ('en_cours', 'resolue', 'escaladee', 'abandonnee')),
    canal_entree               VARCHAR(10) NOT NULL
        CHECK (canal_entree IN ('web', 'mobile', 'app')),
    id_categorie_detectee      INTEGER REFERENCES categorie_sav (id_categorie),
    resume_session              TEXT,
    score_satisfaction          INT CHECK (score_satisfaction BETWEEN 1 AND 5)
);

CREATE TABLE message_chatbot (
    id_message     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_session       INTEGER NOT NULL REFERENCES session_chatbot (id_session),
    date_message      TIMESTAMP NOT NULL DEFAULT now(),
    auteur            VARCHAR(15) NOT NULL
        CHECK (auteur IN ('utilisateur', 'bot')),
    contenu           TEXT NOT NULL,
    type_contenu      VARCHAR(20) NOT NULL
        CHECK (type_contenu IN ('texte', 'choix_rapide', 'redirection', 'action_declenchee')),
    metadata          JSONB
);

CREATE TABLE ticket_sav (
    id_ticket                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_ticket                  VARCHAR(20) NOT NULL UNIQUE,
    id_utilisateur                     INTEGER REFERENCES utilisateur (id_utilisateur),
    id_dossier                          INTEGER REFERENCES dossier (id_dossier),
    id_session_chatbot                  INTEGER REFERENCES session_chatbot (id_session),
    id_categorie                        INTEGER NOT NULL REFERENCES categorie_sav (id_categorie),
    id_agent_assigne                    INTEGER REFERENCES agent (id_agent),
    origine                              VARCHAR(20) NOT NULL CHECK (origine IN (
        'chatbot_escalade', 'utilisateur_direct', 'agent_backoffice', 'appel_telephone', 'email_entrant'
    )),
    canal_contact_souhaite               VARCHAR(15) NOT NULL DEFAULT 'indifferent'
        CHECK (canal_contact_souhaite IN ('email', 'telephone', 'chat_agent', 'indifferent')),
    priorite                              VARCHAR(10) NOT NULL DEFAULT 'normale'
        CHECK (priorite IN ('basse', 'normale', 'haute', 'urgente')),
    titre                                 VARCHAR(200) NOT NULL,
    description_initiale                  TEXT,
    statut                                VARCHAR(25) NOT NULL DEFAULT 'ouvert' CHECK (statut IN (
        'ouvert', 'en_cours', 'en_attente_utilisateur', 'en_attente_interne', 'resolu', 'ferme', 'reouvert'
    )),
    date_creation                          TIMESTAMP NOT NULL DEFAULT now(),
    date_premiere_prise_en_charge          TIMESTAMP,
    date_resolution                        TIMESTAMP,
    date_cloture                           TIMESTAMP,
    score_satisfaction                     INT CHECK (score_satisfaction BETWEEN 1 AND 5)
);

CREATE TABLE historique_ticket (
    id_historique_ticket   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket                INTEGER NOT NULL REFERENCES ticket_sav (id_ticket),
    date_action               TIMESTAMP NOT NULL DEFAULT now(),
    type_action               VARCHAR(30) NOT NULL CHECK (type_action IN (
        'creation', 'changement_statut', 'reassignation', 'message_agent',
        'message_utilisateur', 'canal_contact_utilise', 'cloture', 'reouverture'
    )),
    id_agent                  INTEGER REFERENCES agent (id_agent),
    id_utilisateur            INTEGER REFERENCES utilisateur (id_utilisateur),
    description                TEXT
);

CREATE TABLE notification_agent (
    id_notif_agent            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket                   INTEGER NOT NULL REFERENCES ticket_sav (id_ticket),
    id_agent_destinataire       INTEGER REFERENCES agent (id_agent),
    type_notification            VARCHAR(25) NOT NULL CHECK (type_notification IN (
        'nouvelle_escalade', 'ticket_urgent', 'relance_sans_reponse', 'ticket_reassigne'
    )),
    contenu                      TEXT,
    canal                        VARCHAR(10) NOT NULL
        CHECK (canal IN ('in_app', 'email', 'sms')),
    date_envoi                   TIMESTAMP NOT NULL DEFAULT now(),
    statut_lecture               VARCHAR(10) NOT NULL DEFAULT 'non_lu'
        CHECK (statut_lecture IN ('non_lu', 'lu')),
    date_lecture                 TIMESTAMP
);
