CREATE TABLE contact_email (
    id_contact_email   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket            INTEGER NOT NULL REFERENCES ticket_sav (id_ticket),
    date_envoi             TIMESTAMP NOT NULL DEFAULT now(),
    expediteur             VARCHAR(15) NOT NULL
        CHECK (expediteur IN ('utilisateur', 'agent')),
    id_agent               INTEGER REFERENCES agent (id_agent),
    id_utilisateur         INTEGER REFERENCES utilisateur (id_utilisateur),
    sujet                  VARCHAR(200),
    corps                  TEXT NOT NULL,
    pieces_jointes         JSONB,
    id_email_parent        INTEGER REFERENCES contact_email (id_contact_email)
);

CREATE TABLE contact_telephone (
    id_contact_tel       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket              INTEGER NOT NULL REFERENCES ticket_sav (id_ticket),
    id_agent                INTEGER REFERENCES agent (id_agent),
    id_utilisateur          INTEGER REFERENCES utilisateur (id_utilisateur),
    date_appel               TIMESTAMP NOT NULL DEFAULT now(),
    duree_secondes           INT,
    sens                     VARCHAR(10) NOT NULL
        CHECK (sens IN ('entrant', 'sortant')),
    statut                   VARCHAR(15) NOT NULL
        CHECK (statut IN ('decroche', 'non_repondu', 'messagerie')),
    compte_rendu             TEXT,
    enregistrement_url       VARCHAR(255)
);

CREATE TABLE session_chat_agent (
    id_session_chat          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket                  INTEGER NOT NULL REFERENCES ticket_sav (id_ticket),
    id_agent                    INTEGER NOT NULL REFERENCES agent (id_agent),
    id_utilisateur               INTEGER NOT NULL REFERENCES utilisateur (id_utilisateur),
    date_debut                   TIMESTAMP NOT NULL DEFAULT now(),
    date_fin                     TIMESTAMP,
    statut                       VARCHAR(15) NOT NULL DEFAULT 'en_attente'
        CHECK (statut IN ('en_attente', 'en_cours', 'terminee')),
    temps_attente_secondes       INT
);

CREATE TABLE message_chat_agent (
    id_message_chat   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_session_chat      INTEGER NOT NULL REFERENCES session_chat_agent (id_session_chat),
    date_message           TIMESTAMP NOT NULL DEFAULT now(),
    auteur                  VARCHAR(15) NOT NULL
        CHECK (auteur IN ('utilisateur', 'agent')),
    contenu                 TEXT NOT NULL,
    lu                      BOOLEAN NOT NULL DEFAULT FALSE,
    date_lecture            TIMESTAMP
);
