-- Corpus RAG (Retrieval-Augmented Generation) sur pgvector.
--
-- Ces tables ne sont PAS mappees par des entites JPA : l'embedding est de type
-- `vector` (extension pgvector), inconnu d'Hibernate. L'acces se fait en SQL
-- natif (JdbcTemplate) dans PgVectorStore, donc `ddl-auto: validate` n'a rien a
-- valider ici (aucune entite -> aucune contrainte de correspondance).

CREATE EXTENSION IF NOT EXISTS vector;

-- Un document = un fichier source du corpus (markdown). Le checksum permet une
-- ingestion idempotente : on ne re-embedde un document que si son contenu change.
CREATE TABLE rag_document (
    id_document     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chemin_source   VARCHAR(500) NOT NULL UNIQUE,
    titre           VARCHAR(300),
    url             VARCHAR(500),
    categorie       VARCHAR(100),
    checksum        VARCHAR(64) NOT NULL,
    nb_fragments    INTEGER NOT NULL DEFAULT 0,
    date_ingestion  TIMESTAMP NOT NULL DEFAULT now()
);

-- Un fragment = un morceau de document, vectorise. La dimension 1024 correspond
-- au modele d'embedding voyage-3.5 (verifie). Changer de modele => changer la
-- dimension => nouvelle migration + re-ingestion complete.
CREATE TABLE rag_chunk (
    id_chunk        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_document     INTEGER NOT NULL REFERENCES rag_document (id_document) ON DELETE CASCADE,
    ordre           INTEGER NOT NULL,
    titre_section   VARCHAR(500),
    contenu         TEXT NOT NULL,
    nb_tokens_estimes INTEGER NOT NULL DEFAULT 0,
    embedding       vector(1024) NOT NULL
);

CREATE INDEX idx_rag_chunk_document ON rag_chunk (id_document);

-- Index ANN pour la recherche par similarite cosinus (operateur <=>).
-- HNSW : bon compromis rappel/latence, construction possible sur table vide.
CREATE INDEX idx_rag_chunk_embedding
    ON rag_chunk USING hnsw (embedding vector_cosine_ops);
